// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader');

const nls_ts = {
    description: 'description',
    displayName: 'displayName',
    command: {
        copyLink: 'command.md.link.copy',
        createSection: 'command.md.section.create',
        deleteHelptag: 'command.md.helptag.delete',
        deleteSection: 'command.md.section.delete',
        generateBreadcrumbs: 'command.html.breadcrumbs.generate',
        generateContexts: 'command.fe.context.generate',
        generateHelpMaps: 'command.fe.helptag.generate',
        moveSection: 'command.md.section.move',
        pasteLink: 'command.md.link.paste',
        pasteImage: 'command.md.image.paste',
        reindexDirectories: 'command.fs.naming.update',
        reindexFigures: 'command.md.link.rebuild',
        renameSection: 'command.md.section.update',
        updateHelptag: 'command.md.helptag.update',
        wipeEmptyDirectories: 'command.fs.empty.wipe',
    },
    submenu: {
        context: 'submenu.context',
        diplodoc: 'submenu.diplodoc',
        generators: 'submenu.generators',
        reindexier: 'submenu.reindexier',
        helptag: 'submenu.helptag',
    },
    plugin: {
        breadcrumb: {
            generate: {
                error: {
                    detail: 'plugin.breadcrumb.generate.error.detail',
                    foldernotfound: 'plugin.breadcrumb.generate.error.foldernotfound',
                },
                info: {
                    success: 'plugin.breadcrumb.generate.info.success',
                },
            },
        },
        context: {
            delete: {
                confirm: {
                    button: 'plugin.context.delete.confirm.button',
                    prompt: 'plugin.context.delete.confirm.prompt',
                },
                dialog: {
                    placeholder: 'plugin.context.delete.dialog.placeholder',
                },
                error: {
                    critical: 'plugin.context.delete.error.critical',
                },
                info: {
                    success: 'plugin.context.delete.info.success',
                },
            },
            generate: {
                error: {
                    notfound: 'plugin.context.generate.error.notfound',
                },
                info: {
                    success: 'plugin.context.generate.info.success',
                },
            },
            update: {
                change: {
                    error: {
                        validation: 'plugin.context.update.change.error.validation',
                    },
                    inputprompt: 'plugin.context.update.change.inputprompt',
                },
                error: {
                    critical: 'plugin.context.update.error.critical',
                    incorrectSection: 'plugin.context.update.error.incorrectSection',
                },
                info: {
                    success: 'plugin.context.update.info.success',
                },
                new: {
                    actionplaceholder: 'plugin.context.update.new.actionplaceholder',
                    add: {
                        inputplaceholder: 'plugin.context.update.new.add.inputplaceholder',
                        inputprompt: 'plugin.context.update.new.add.inputprompt',
                    },
                    addnewcontext: 'plugin.context.update.new.addnewcontext',
                    error: {
                        empty: 'plugin.context.update.new.error.empty',
                    },
                    placeholder: 'plugin.context.update.new.placeholder',
                    prompt: 'plugin.context.update.new.prompt',
                },
            },
            wipe: {
                success: 'plugin.context.wipe.success',
            },
        },
        helpmap: {
            generate: {
                error: {
                    critical: 'plugin.helpmap.generate.error.critical',
                    emptypath: 'plugin.helpmap.generate.error.emptypath',
                },
                info: {
                    success: 'plugin.helpmap.generate.info.success',
                },
                warning: {
                    nothingfound: 'plugin.helpmap.generate.warning.nothingfound',
                },
            },
        },
        helptag: {
            delete: {
                confirm: {
                    button: 'plugin.helptag.delete.confirm.button',
                    title: 'plugin.helptag.delete.confirm.title',
                },
                error: {
                    critical: 'plugin.helptag.delete.error.critical',
                },
                info: {
                    success: 'plugin.helptag.delete.info.success',
                },
            },
            update: {
                error: {
                    critical: 'plugin.helptag.update.error.critical',
                    empty: 'plugin.helptag.update.error.empty',
                    incorrectSection: 'plugin.helptag.update.error.incorrectSection',
                },
                info: {
                    success: 'plugin.helptag.update.info.success',
                },
                placeholder: {
                    add: 'plugin.helptag.update.placeholder.add',
                },
                prompt: {
                    add: 'plugin.helptag.update.prompt.add',
                },
            },
        },
        link: {
            copy: {
                info: {
                    success: 'plugin.link.copy.info.success',
                },
            },
            paste: {
                error: {
                    critical: 'plugin.link.paste.error.critical',
                    emptybuffer: 'plugin.link.paste.error.emptybuffer',
                },
            },
        },
        section: {
            create: {
                error: {
                    critical: 'plugin.section.create.error.critical',
                    incorrectSection: 'plugin.section.create.error.incorrectSection',
                },
                info: {
                    success: 'plugin.section.create.info.success',
                },
            },
            delete: {
                confirmation: {
                    text: 'plugin.section.delete.confirmation.text',
                    title: 'plugin.section.delete.confirmation.title',
                },
                error: {
                    critical: 'plugin.section.delete.error.critical',
                    incorrectSection: 'plugin.section.delete.error.incorrectSection',
                },
                info: {
                    success: 'plugin.section.delete.info.success',
                },
            },
            move: {
                error: {
                    critical: 'plugin.section.move.error.critical',
                    incorrectSection: 'plugin.section.move.error.incorrectSection',
                    recursive: 'plugin.section.move.error.recursive',
                    sectionexists: 'plugin.section.move.error.sectionexists',
                    self: 'plugin.section.move.error.self',
                },
                info: {
                    success: 'plugin.section.move.info.success',
                },
                label: {
                    after: 'plugin.section.move.label.after',
                },
                placeholder: {
                    end: 'plugin.section.move.placeholder.end',
                    start: 'plugin.section.move.placeholder.start',
                    target: 'plugin.section.move.placeholder.target',
                    targetfolder: 'plugin.section.move.placeholder.targetfolder',
                },
                warning: {
                    broken: 'plugin.section.move.warning.broken',
                },
            },
            reindex: {
                info: {
                    success: 'plugin.section.reindex.info.success',
                },
                progress: {
                    text: 'plugin.section.reindex.progress.text',
                },
                warning: {
                    button: 'plugin.section.reindex.warning.button',
                    text: 'plugin.section.reindex.warning.text',
                },
            },
            rename: {
                error: {
                    critical: 'plugin.section.rename.error.critical',
                    folderexists: 'plugin.section.rename.error.folderexists',
                    interrupted: 'plugin.section.rename.error.interrupted',
                    isnotsection: 'plugin.section.rename.error.isnotsection',
                },
                info: {
                    success: 'plugin.section.rename.info.success',
                },
            },
        },
        reindex: {
            figures: {
                info: {
                    success: 'plugin.reindex.figures.info.success',
                    successDetailed: 'plugin.reindex.figures.info.successDetailed',
                    failDetailed: 'plugin.reindex.figures.info.failDetailed',
                },
            },
        },
    },
    paste: {
        image: {
            error: {
                noactiveeditor: 'paste.omage.error.noactiveeditor',
            },
            warning: {
                mdfileonly: 'paste.image.warning.mdfileonly',
                emptybuffer: 'paste.image.warning.emptybuffer',
            },
        },
    },
    screenshot: {
        description: {
            placeholder: 'screenshot.description.placeholder',
        },
        name: {
            prompt: 'screenshot.name.prompt',
            error: {
                wrongcharacters: 'screenshot.name.error.wrongcharacters',
            },
        },
        saved: {
            info: 'screenshot.saved.info',
        },
        error: {
            notsaved: 'screenshot.error.notsaved',
            alreadyexists: {
                async: 'screenshot.error.alreadyexists.async',
            },
        },
    },
    filename: {
        error: {
            alreadyexists: 'filename.error.alreadyexists',
        },
    },
};

module.exports = { nls_ts, translate };
